services:
  dbelec-mysql:
    restart: always
    image: mysql:8.0.28
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=R2V2MDF1YzEwbjQ
      - MYSQL_DATABASE=databaselectiva
      - MYSQL_USER=dbelecuser
      - MYSQL_PASSWORD=KnNpbWVhcGl0ZXN0Kg
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    ports:
      - 13306:3306
      - 8080:8080
      - 19080:9080
    volumes:
      - dbelec-prod:/var/lib/mysql
    networks:
      - backend
# Names our volume
volumes:
  dbelec-prod:
networks:
  backend: